POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "rafael@rafael.com",
  "password": "teste"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "rafael",
  "email": "rafael@rafael.com",
  "senha": "teste"
}

###
POST http://localhost:3000/groups
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjI2LCJuYW1lIjoicmFmYWVsIiwiZ3JvdXBzX2NyZWF0ZV9tb3VudCI6MCwiY3JlYXRlZF9hdCI6IjIwMjEtMTEtMTZUMDA6MTE6MTIuMTQ4WiJ9LCJpYXQiOjE2MzcwMjQxMzksImV4cCI6MTYzNzA1MjkzOX0.zwaXF933pOVLywWqlK9YUCF5b171eEO13Sfpo9m8g8I

{
  "name": "grupo do fei 11"
}