version: '3'

services:

  app:
    image: rafaelcaval1/node:0.0.1
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: nest-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - network-chat-tallos

  db:
    build: .docker/postgres
    container_name: db_banco
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nest_api
    volumes:
      - ./.docker/postgres/dbdata:/var/lib/postgresql/data
    depends_on:
      - app
    networks:
      - network-chat-tallos

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db
    networks:
      - network-chat-tallos
networks:
  network-chat-tallos:
    driver: bridge
