GET http://localhost:3000/groups/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjI2LCJuYW1lIjoicmFmYWVsIiwiZ3JvdXBzX2NyZWF0ZV9tb3VudCI6MCwiY3JlYXRlZF9hdCI6IjIwMjEtMTEtMTZUMDA6MTE6MTIuMTQ4WiJ9LCJpYXQiOjE2MzcwMjQxMzksImV4cCI6MTYzNzA1MjkzOX0.zwaXF933pOVLywWqlK9YUCF5b171eEO13Sfpo9m8g8I

###
POST http://localhost:3000/groups/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjI2LCJuYW1lIjoicmFmYWVsIiwiZ3JvdXBzX2NyZWF0ZV9tb3VudCI6MCwiY3JlYXRlZF9hdCI6IjIwMjEtMTEtMTZUMDA6MTE6MTIuMTQ4WiJ9LCJpYXQiOjE2MzcwMjQxMzksImV4cCI6MTYzNzA1MjkzOX0.zwaXF933pOVLywWqlK9YUCF5b171eEO13Sfpo9m8g8I
Content-Type: application/json

{
    "name": "Grupo do fei 122"
}
###
DELETE http://localhost:3000/groups/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjMsIm5hbWUiOiJ0ZXN0ZSIsImdyb3Vwc19jcmVhdGVfbW91bnQiOjAsImNyZWF0ZWRfYXQiOiIyMDIxLTExLTA3VDAyOjUyOjAwLjc2NFoifSwiaWF0IjoxNjM2Mjg1ODMzLCJleHAiOjE2MzYzMTQ2MzN9.rLjRXWYWor-3F0pFctJqFPjNxyZQsmMxhRVcT6v3VDk