GET http://localhost:3000/groups/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjUsIm5hbWUiOiJ0ZXN0ZSIsImdyb3Vwc19jcmVhdGVfbW91bnQiOjAsImNyZWF0ZWRfYXQiOiIyMDIxLTExLTA3VDEzOjI3OjAyLjEwNloifSwiaWF0IjoxNjM2MzIyMjc1LCJleHAiOjE2MzYzNTEwNzV9.3ZrpGSYt0D4vOs0sxTWRQuVm7dhpuEvReQfSh04JJrQ

###
POST http://localhost:3000/groups/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjUsIm5hbWUiOiJ0ZXN0ZSIsImdyb3Vwc19jcmVhdGVfbW91bnQiOjAsImNyZWF0ZWRfYXQiOiIyMDIxLTExLTA3VDEzOjI3OjAyLjEwNloifSwiaWF0IjoxNjM2MzIyMjc1LCJleHAiOjE2MzYzNTEwNzV9.3ZrpGSYt0D4vOs0sxTWRQuVm7dhpuEvReQfSh04JJrQ
Content-Type: application/json

{
    "name": "Grupo do fei"
}
###
DELETE http://localhost:3000/groups/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjMsIm5hbWUiOiJ0ZXN0ZSIsImdyb3Vwc19jcmVhdGVfbW91bnQiOjAsImNyZWF0ZWRfYXQiOiIyMDIxLTExLTA3VDAyOjUyOjAwLjc2NFoifSwiaWF0IjoxNjM2Mjg1ODMzLCJleHAiOjE2MzYzMTQ2MzN9.rLjRXWYWor-3F0pFctJqFPjNxyZQsmMxhRVcT6v3VDk