GET http://localhost:3000/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjI2LCJuYW1lIjoicmFmYWVsIiwiZ3JvdXBzX2NyZWF0ZV9tb3VudCI6MCwiY3JlYXRlZF9hdCI6IjIwMjEtMTEtMTZUMDA6MTE6MTIuMTQ4WiJ9LCJpYXQiOjE2MzcwMjQxMzksImV4cCI6MTYzNzA1MjkzOX0.zwaXF933pOVLywWqlK9YUCF5b171eEO13Sfpo9m8g8I

###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "email": "rafael@rafael.com",
    "name": "teste",
    "senha": "teste"
}
###
DELETE http://localhost:3000/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjMsIm5hbWUiOiJ0ZXN0ZSIsImdyb3Vwc19jcmVhdGVfbW91bnQiOjAsImNyZWF0ZWRfYXQiOiIyMDIxLTExLTA3VDAyOjUyOjAwLjc2NFoifSwiaWF0IjoxNjM2MjUzNTI3LCJleHAiOjE2MzYyODIzMjd9.YYQuRffKVYqYC8dx-lc_Npso4OU50e4P5lA99L5_W4U