version: '3'

services:

  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: front_tallos
    tty: true
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app