POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "teste"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "rafael",
  "email": "razcxf12312312ael@rfasdafael.com",
  "senha": "teste"
}

###
POST http://localhost:3000/groups
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjIzLCJuYW1lIjoidGVzdGUiLCJncm91cHNfY3JlYXRlX21vdW50IjowLCJjcmVhdGVkX2F0IjoiMjAyMS0xMS0xNVQyMTo0NDozNS44NDJaIn0sImlhdCI6MTYzNzAxMjc0NSwiZXhwIjoxNjM3MDQxNTQ1fQ.HVO5JAfWngHjbIKgyWNSOF3PIzR7ux9hqzxhm775tmM

{
  "name": "grupo do fei 3"
}