GET http://localhost:3000/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjEsIm5hbWUiOiJ0ZXN0ZSIsImdyb3Vwc19jcmVhdGVfbW91bnQiOjAsImNyZWF0ZWRfYXQiOiIyMDIxLTExLTA5VDIxOjE1OjE1LjQ3M1oifSwiaWF0IjoxNjM2NDkyNTI0LCJleHAiOjE2MzY1MjEzMjR9.0_5_Ete331wzzQC9CkL7QUl2Pwet_vXeoazz6xsRPfQ

###
POST http://54.245.245.59:3000/users/
Content-Type: application/json

{
    "email": "rafael@rafael.com",
    "name": "teste",
    "senha": "teste"
}
###
DELETE http://localhost:3000/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRm9ybWF0ZWQiOnsiaWQiOjMsIm5hbWUiOiJ0ZXN0ZSIsImdyb3Vwc19jcmVhdGVfbW91bnQiOjAsImNyZWF0ZWRfYXQiOiIyMDIxLTExLTA3VDAyOjUyOjAwLjc2NFoifSwiaWF0IjoxNjM2MjUzNTI3LCJleHAiOjE2MzYyODIzMjd9.YYQuRffKVYqYC8dx-lc_Npso4OU50e4P5lA99L5_W4U